name: CI/CD Pipeline
# This is a comment added to retrigger the workflow

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: yilmazsekci
        password: DElete_1907

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: yilmazsekci/text-manipulation:latest

    - name: Run Docker container
      run: docker run --rm yilmazsekci/text-manipulation:latest
